# Site settings
title: markiewski.com
description: A description of my personal website.
baseurl: "markiewski,com" # the subpath of your site, e.g. /blog
url: "https://markiewski.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-theme-primer # This is a basic theme. You can change it or remove it.
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
